### PR TITLE
Fix extension of class properties

### LINKED ISSUE #25: False Positive error when extending a deprecated method
In the following scenario, when calling `method()` on the `New` class, the plugin should not report an error, but it does:

```typescript
class Old {
  /** @deprecated */
  method(): void {
  }
}

class New extends Old {
  method(): void {
  }
}

new Old().method(); // should throw an error -> everything fine
new New().method(); // should not throw an error -> still throws an error
```

### PR DESCRIPTION
**Pull request by json-derulo**
Fixes https://github.com/gund/eslint-plugin-deprecation/issues/25

### CODE REVIEW

**Comment by json-derulo** [comment]
@Delagen would be great if you could review this :)

**Comment by delagen** [comment]
@json-derulo partially merged via 4a87a42e22ca84ff606dc6b346a14198d81f3c2c. Thanks.

**Comment by delagen** [comment]
Published in npm as 1.3.1

**Comment by json-derulo** [comment]
@Delagen thanks for merging this. However, as I just found out in a real project of mine, now the wrong function signature is used, which brought up a lot of new false positive errors. Unfortunately, there are currently no test cases covering this.

Could you revert the changes of this PR and publish a new version?

I will add additional test cases for the new errors, and will try to fix the issue in the meantime. I'm very sorry for this.

**Comment by json-derulo** [comment]
The variable assignment I removed seems to be necessary sometimes. I had no luck so far finding out, which is the right condition to do the assignment. Will continue tomorrow.

**Comment by delagen** [comment]
reverted, some deps updates, 1.3.2

**Pull request closed without merging**
